version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./database:/app/database
      - ./upload:/app/upload
    ports:
      - "3001:3000"
    restart: unless-stopped

  ngrok:
    image: ngrok/ngrok:latest
    restart: unless-stopped
    env_file:
      - .env
    command: http --domain=${DOMAIN} 3001
    network_mode: "host"